In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("updated_f1_lap_time_dataset.csv")
df.head()

,Unnamed: 0,year,round,circuit_name,circuit_country,driver_id,lap_number,estimated_horsepower,car_weight,track_temperature,driving_aggression,fuel_load_percent,lap_time_sec,tire_compound_hard,tire_compound_medium,tire_compound_soft
0,0,2010,1,0,0,0,1,0.072289,0.737374,0.500000,0.466181,0.583323,123.366,False,True,False
1,1,2010,1,0,0,1,1,0.040161,0.828283,0.500000,0.908827,0.738912,125.394,False,False,True
2,2,2010,1,0,0,2,1,0.975904,0.878788,0.958333,0.252486,0.490736,126.758,True,False,False
3,3,2010,1,0,0,3,1,0.248996,0.565657,0.708333,0.695637,0.365281,128.063,False,True,False
4,4,2010,1,0,0,4,1,0.983936,0.282828,0.375000,0.795228,0.038375,128.558,True,False,False